### ISSUE TITLE
fix cache key

### ISSUE THREAD

**Issue by drcmda** [cocoss-org/co-media#1]
https://github.com/cocoss-org/co-media/blob/02d40d9112e718f5112b55f61383a2bbc1b71a27/src/use-media-devices.ts#L81

this better be a unique cache key, or else it could conflict with user-land cache.

```jsx
suspend(async () => {
  // ...
}, ["cocoss-org/co-media/useMediaDevices"])
```

**Comment by bbohlender** [comment]
Yeah right 👍 😄
Fixed in version 1.0.1
